# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/first_project',
                'doc_host': 'https://michaeldini.github.io',
                'git_url': 'https://github.com/michaeldini/first_project',
                'lib_path': 'first_project'},
  'syms': {'first_project.core': {'first_project.core.foo': ('core.html#foo', 'first_project/core.py')}}}
