# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_first_project.ipynb.

# %% auto 0
__all__ = ['what_is_the_time']

# %% ../nbs/00_first_project.ipynb 3
import datetime as dt 
def what_is_the_time(): return dt.datetime.strftime(dt.datetime.now(), '%Y-%m-%d')

